### ISSUE TITLE
Location Page Events Widget Not Wrapping on Mobile

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#297]
![image](https://user-images.githubusercontent.com/1933400/38555720-2eb8a3c8-3c95-11e8-8f62-c427406afd73.png)

**Comment by mxsnyder** [comment]
`flex-direction: column` at `$screen-md` and below.

**Comment by martypowell** [comment]
@mxsnyder i think the markup, maybe just need the `flex flex-column` classes add. See the homepage for an example.

**Comment by danfox01** [comment]
Let me know if this is confirmed. I can assign it out for someone to update the markup.

**Comment by mxsnyder** [comment]
It's not the markup, there's a media query doing this in `homepage.min.css`:

```CSS
@media (max-width: 991px)
.events-wrapper .container .row.flex {
    display: block;
}
```
